defaults: &defaults
  docker:
    - image: circleci/python:3.6.4

version: 2
jobs:
  deps:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: run tests
          command: |
            source venv/bin/activate
            make test

  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: build code archive
          command: |
            source venv/bin/activate
            make build

      - persist_to_workspace:
          root: src
          paths:
            - bundle.zip

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp

      # Install AWS CLI
      - run: sudo pip install -q awscli --upgrade

      - run:
          name: copy build to s3
          command: |
            aws s3 cp /tmp/bundle.zip s3://slack-pivotal-tracker-bot/releases/slack-pivotal-tracker-bot-latest.zip --acl public-read

  deploy_version_tag:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp

      # Install AWS CLI
      - run: sudo pip install -q awscli --upgrade

      - run:
          name: copy tagged build to s3
          command: |
            aws s3 cp /tmp/bundle.zip s3://slack-pivotal-tracker-bot/releases/slack-pivotal-tracker-bot-${CIRCLE_TAG}.zip --acl public-read

workflows:
  version: 2
  pipeline:
    jobs:
      - deps:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - deps
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - deps
            - test
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy_version_tag:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.+)?/
            branches:
              ignore: /.*/
